### ISSUE TITLE
Formatting date value as entered

### ISSUE THREAD

**Issue by johnantoni** [duetds/date-picker#45]
Hi, is it possible to format the date when entering it in the text box or should you be only changing the date via the control?

**Comment by WickyNilliams** [comment]
If I understand the question, you can manually enter dates. By default it accepts ISO 8601 dates (YYYY-MM-DD), but this can be changed to any format by supplying a dateAdapter. There's an example of this in the docs.

Unless you mean something else?

**Comment by johnantoni** [comment]
I've tried getting the dateAdapter to work but only the format function is working.

Here's my implementation:

      <duet-date-picker
        :identifier="inputId"
        :class="{ 
          'is-invalid': !disabled && errors[0], 
        }"
        :value="value"
        v-on="maskedInputEvents()"
        :disabled="isReadOnly(readonly||disabled)"
        :localization.prop="localization()"
        :dateAdapter.prop="dateAdapter"
      />


    public dateAdapter = {
      parse(value = '', createDate: any) {
        const matches = value.match(/^(\d{4})\-(\d{1,2})\-(\d{1,2})$/);
    
        if (matches) {
          return createDate(matches[3], matches[2], matches[1]);
        }      
      },
      format(date: any) {
        return `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
      }
    }

**Comment by WickyNilliams** [comment]
Hmm, can you please explain a little more what you are expecting here? Wasn't the question around formatting, so it's confusing to see you say formatting is working...

Your code looks good to me, though it duplicates the default behaviour and is therefore redundant.

**Comment by johnantoni** [comment]
Sorry, ignore the code I was trying to understand how the parse and format methods were working.

Currently you can select a date with the date picker which returns a date in ISO format.

However when you enter the date via keyboard it doesn't automatically convert it into an ISO format so I'm trying to figure out how to do that so if you enter 20020202 it converts it to 2002-02-02.

I tried using the v-mask plugin with the duet date control but that's not returning a value.

Do you have any idea how this could be done, trying to reformat as you type

**Comment by WickyNilliams** [comment]
Ah I see! We don't support auto formatting like that. The `parse` function accepts a string (what the user entered in the input) and returns a Date object (used as the new value of the picker). Whilst `format` does the opposite,  it accepts a Date object (selected from the calendar) and returns a string (what to set the input's value to). See the localisation example on the docs site, where we configure the picker to use Finnish date format.

You could maybe do some auto-formatting yourself by listening to input events. But we won't support it in the picker itself - I always find that auto-formatting breaks keyboard functionality in some ways whether that's due to copying, pasting, using home/end, shift and arrows. There's almost always an issue.

I don't know Vue so I don't know the v-mask library. I assume you'd need to add some glue code if you wanted to use that, but that's outside the scope of this issue tracker :)

**Comment by johnantoni** [comment]
Thanks @WickyNilliams, managed to do it via the duetBlur event which seems to work ok.

          duetBlur(event: any) {
            const value = _vm.value;
            const matches = value.match(/^(\d{0,4})(\d{0,2})(\d{0,2})$/);
            if (matches) {
              _vm.$emit('input', `${matches[1]}-${matches[2]}-${matches[3]}`);
            } else {
              _vm.$emit('input', _vm.value);  
            }
          },

**Comment by WickyNilliams** [comment]
Glad to hear it!
